# Generated by Django 3.2 on 2021-04-12 17:28

import django.core.validators
from django.db import migrations, models
import koronavirus.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev_statu', models.CharField(max_length=100, unique=True, verbose_name='Stát')),
                ('zkratka_statu', models.CharField(max_length=10, verbose_name='Zkratka státu')),
                ('vlajka', models.ImageField(blank=True, null=True, upload_to=koronavirus.models.image_path, verbose_name='Vlajka státu')),
                ('forma_statu', models.CharField(blank=True, choices=[('monarchie', 'Monarchie'), ('konstitucni-monarchie', 'Konstituční monarchie'), ('parlamentne-konstitucni-monarchie', 'Parlamentně konstituční monarchie'), ('demokracie', 'Demokracie'), ('diktatura', 'Diktatura'), ('jine', 'jiné')], max_length=100, null=True, verbose_name='Forma státu')),
                ('pocet_obyvatel', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Počet obyvatel')),
                ('rozloha', models.IntegerField(blank=True, null=True, verbose_name='Rozloha')),
                ('text', models.TextField(blank=True, null=True, verbose_name='O státu')),
            ],
            options={
                'ordering': ['nazev_statu'],
            },
        ),
        migrations.CreateModel(
            name='Naockovani',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pocet_naockovanych', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Počet naočkovaných')),
                ('pocet_umrti_po_ockovani', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Počet umrtí po očkování')),
                ('dominantni_vakcina', models.CharField(blank=True, choices=[('pfizer-biontech', 'Pfizer-BioNTech'), ('moderna', 'Moderna'), ('johnson-&-johnson', 'Johnson & Johnson'), ('astrazeneca', 'AstraZeneca'), ('novavax', 'Novavax'), ('sputnik-v', 'Sputnik V'), ('sinovac-biotech', 'Sinovac Biotech'), ('jine', 'jiné')], help_text='Vyberte dominantní vakcínu', max_length=40, verbose_name='Dominantní vakcína')),
                ('datum', models.DateField(auto_now=True)),
                ('stat', models.ManyToManyField(help_text='Vyberte stát', to='koronavirus.Stat')),
            ],
            options={
                'ordering': ['pocet_naockovanych'],
            },
        ),
        migrations.CreateModel(
            name='Nakazeni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pocet_nakazenych', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Počet nakažených')),
                ('pocet_umrti', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Počet úmrtí')),
                ('datum', models.DateField(auto_now=True)),
                ('stat', models.ManyToManyField(help_text='Vyberte stát', to='koronavirus.Stat')),
            ],
            options={
                'ordering': ['pocet_nakazenych'],
            },
        ),
    ]
