# Generated by Django 3.2 on 2021-04-12 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('koronavirus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stat',
            name='forma_statu',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Forma státu'),
        ),
    ]
