# Generated by Django 3.2 on 2021-04-12 18:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('koronavirus', '0002_alter_stat_forma_statu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stat',
            name='rozloha',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='Rozloha v km čtverečních'),
        ),
    ]
