# Generated by Django 3.2 on 2021-05-11 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('koronavirus', '0003_alter_stat_rozloha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nakazeni',
            name='stat',
        ),
        migrations.RemoveField(
            model_name='naockovani',
            name='stat',
        ),
        migrations.AddField(
            model_name='stat',
            name='nakazeni',
            field=models.ManyToManyField(to='koronavirus.Nakazeni', verbose_name='Zadej nakažené'),
        ),
        migrations.AddField(
            model_name='stat',
            name='naockovani',
            field=models.ManyToManyField(to='koronavirus.Naockovani', verbose_name='Zadej naočkované'),
        ),
    ]
